plugins {
    id "com.gradleup.shadow" version "9.3.1"
}

architectury {
    platformSetupLoomIde()
    fabric()
}

base {
    archivesName = rootProject.mod_id + "-fabric"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:${rootProject.fabric_loader_version}"
    modApi "net.fabricmc.fabric-api:fabric-api:${rootProject.fabric_api_version}"
    modApi "dev.architectury:architectury-fabric:${rootProject.architectury_version}"
    modImplementation "maven.modrinth:SJu6sklj:HYOSUnpY"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionFabric")) { transitive = false }
}

processResources {
    def replaceProperties = [
        mod_id: rootProject.mod_id,
        mod_name: rootProject.mod_name,
        mod_license: rootProject.mod_license,
        mod_version: rootProject.mod_version,
        mod_authors: rootProject.mod_authors,
        mod_description: rootProject.mod_description,
        minecraft_version: rootProject.minecraft_version,
        architectury_version: rootProject.architectury_version,
        fabric_loader_version: rootProject.fabric_loader_version,
        fabric_api_version: rootProject.fabric_api_version
    ]
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
