plugins {
    id "com.gradleup.shadow" version "9.3.1"
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    forge {
        mixinConfig "cts_compats.mixins.json"
    }
}

base {
    archivesName = rootProject.mod_id + "-forge"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.minecraft_version}-${rootProject.forge_version}"
    modImplementation "dev.architectury:architectury-forge:${rootProject.architectury_version}"
    modImplementation "maven.modrinth:SJu6sklj:fhdOSK5I"

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.4"))
    implementation(include("io.github.llamalad7:mixinextras-forge:0.5.4"))
    modCompileOnly "curse.maven:polymixin-1670134:8744788"

    modCompileOnly "curse.maven:quark-243121:6427817"
    modCompileOnly "curse.maven:immersive-weathering-forge-592449:6116941"
    modCompileOnly "curse.maven:lets-do-meadow-821483:6467344"
    modCompileOnly "curse.maven:vanillabackport-417430:8229712"
    modCompileOnly "curse.maven:biomes-o-plenty-220318:6364065"
    modCompileOnly "curse.maven:project-vibrant-journeys-300297:8198495"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

processResources {
    def replaceProperties = [
        minecraft_version: rootProject.minecraft_version,
        minecraft_version_range: rootProject.minecraft_version_range,
        forge_version: rootProject.forge_version,
        forge_version_range: rootProject.forge_version_range,
        loader_version_range: rootProject.loader_version_range,
        mod_id: rootProject.mod_id,
        mod_name: rootProject.mod_name,
        mod_license: rootProject.mod_license,
        mod_version: rootProject.mod_version,
        mod_authors: rootProject.mod_authors,
        mod_description: rootProject.mod_description
    ]
    inputs.properties replaceProperties

    filesMatching("META-INF/mods.toml") {
        expand replaceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    inputFile.set shadowJar.archiveFile
    dependsOn shadowJar
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
